#
# Define the build matrix
#
# Travis defaults to building on Ubuntu Precise when building on
# Linux. We need Trusty in order to get up to date versions of
# cmake and g++.
#

env:
  global:
    - app_id=inputstream.adaptive.testing
    - secure: "cEcDRo+aWtu0+qCS7oE7bZ23OzbFvsdT1I9P/W2i4VBU9FfDVxuXjX8rG3kUrN7xIxJnEWrJRtrhOHOVjzqZ5tnBsbTLS4mbII4HtPpGpOpxOdnDzeyOa93UgAyMD/SWUFzN/vhgn/LtG0oMqZcQDj7L4ccMkjz4h7075iMxQhSo8vmNyDIpjGwFrHFfifXSZoc0oZsszqXauxLFvPsaXpuTeO86iQdrJ4zUJw+OVnASD6UtQm1LcunJ3N8HsgGKzZGOjUZ2ZxhAf/+00pTOozh6nrlguPs2CgJuHC6J579dckT7OjkjTeGFbqH7bEITQpyH35tXffDs6lptpdcpLjp7m8McAG47CCAyYKmyKRMxTB9M5r4b9QwGsSCO9IxEQQHi/c+WR+bUOp/bYaVYygsJTT+1I0a8mrJ+vOrjhfK1O5pNKNv6Vd1WlTdo8pG6EXMw/P/HpNFpVfHPP0zCNbG+lBCogfaIwVkU+xNWCSXPZC0BbG8Jl/14W1M5scB4sFIYGtdsljOyHYbYTARpwnQS/ar+JpbNOUPkk+/NmKA3YOCQoVi69w/FK4SJR+2e0PCUwES86plYFkg5DzqmR4rpSVshe7dpq6Fl163ktQIfJRvQPvqdfRd/yYtJAMAls7Z7X5UfpjSQR97ndvOx2/cwkdxRTW3dKmWO5rQLhu0="
    
#
# The addon source is automatically checked out in $TRAVIS_BUILD_DIR,
# we'll put the Kodi source on the same level
#

jobs:
  include:
    - stage: compile
      os: linux
      dist: xenial
      language: cpp
      sudo: required
      compiler: gcc
      env:
        - ANDROID="" ARCH="aarch64"
      workspaces:
        create:
          name: linux-aarch64
          paths: .

    - os: linux
      dist: xenial
      language: cpp
      sudo: required
      compiler: gcc
      env:
        - ANDROID="" ARCH="armv7"
      workspaces:
        create:
          name: linux-armv7
          paths: .

    - os: linux
      dist: xenial
      language: cpp
      sudo: required
      compiler: gcc
      env:
        - ANDROID="" ARCH="x86_64"
      workspaces:
        create:
          name: linux-x86_64
          paths: .

    - os: linux
      dist: xenial
      language: cpp
      sudo: required
      compiler: gcc
      env:
        - ANDROID=" --android" ARCH="aarch64"
      workspaces:
        create:
          name: android-aarch64
          paths: .

    - os: linux
      dist: xenial
      language: cpp
      sudo: required
      compiler: gcc
      env:
        - ANDROID=" --android" ARCH="armv7"
      workspaces:
        create:
          name: android-armv7
          paths: .

    - stage: deploy
      workspaces:
        use:
          - linux-aarch64
          - linux-armv7
          - linux-x86_64
          - android-aarch64
          - android-armv7
      install:
        - sudo apt-get update && sudo apt-get -y update
        - sudo apt install -y --no-install-recommends build-essential git unzip python3 python3-pip
        - sudo pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - cd $HOME/.deploy
        #- git checkout -b travis-build-$TRAVIS_BUILD_NUMBER
        - mkdir -p $TRAVIS_BUILD_DIR/.build
        - ls $TRAVIS_BUILD_DIR
        - > 
          for f in $TRAVIS_BUILD_DIR/*.zip; do
            unzip $f -d $TRAVIS_BUILD_DIR/.build/${f%.*}
            python3 $TRAVIS_BUILD_DIR/manage_repo.py $TRAVIS_BUILD_DIR -b $TRAVIS_BUILD_DIR/.build/${f%.*}/${app_id}
          done
        #- unzip $HOME/$(cat $HOME/zip_name.txt) -d  $TRAVIS_BUILD_DIR/.build
        #- python $TRAVIS_BUILD_DIR/manage_repo.py $TRAVIS_BUILD_DIR -b $TRAVIS_BUILD_DIR/.build/${app_id}
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
        - git add .
        - git commit --allow-empty -m "$TRAVIS_COMMIT_MESSAGE"
        - git push
        #- git push --set-upstream origin travis-build-$TRAVIS_BUILD_NUMBER

install:
  - sudo apt-get update && sudo apt-get -y update
  - sudo apt install -y --no-install-recommends build-essential git cmake unzip aria2 default-jdk python3

script:
  - bash -x $TRAVIS_BUILD_DIR/build_scripts/build-ia.sh
    --kodiversion leia
    --no-apt-install
    --arch $ARCH 
    $ANDROID
  - mv $HOME/*.zip $TRAVIS_BUILD_DIR
