os: linux
dist: xenial
language: cpp
compiler: gcc
env:
  global:
    - APP_ID=inputstream.adaptive.testing
    - secure: "cEcDRo+aWtu0+qCS7oE7bZ23OzbFvsdT1I9P/W2i4VBU9FfDVxuXjX8rG3kUrN7xIxJnEWrJRtrhOHOVjzqZ5tnBsbTLS4mbII4HtPpGpOpxOdnDzeyOa93UgAyMD/SWUFzN/vhgn/LtG0oMqZcQDj7L4ccMkjz4h7075iMxQhSo8vmNyDIpjGwFrHFfifXSZoc0oZsszqXauxLFvPsaXpuTeO86iQdrJ4zUJw+OVnASD6UtQm1LcunJ3N8HsgGKzZGOjUZ2ZxhAf/+00pTOozh6nrlguPs2CgJuHC6J579dckT7OjkjTeGFbqH7bEITQpyH35tXffDs6lptpdcpLjp7m8McAG47CCAyYKmyKRMxTB9M5r4b9QwGsSCO9IxEQQHi/c+WR+bUOp/bYaVYygsJTT+1I0a8mrJ+vOrjhfK1O5pNKNv6Vd1WlTdo8pG6EXMw/P/HpNFpVfHPP0zCNbG+lBCogfaIwVkU+xNWCSXPZC0BbG8Jl/14W1M5scB4sFIYGtdsljOyHYbYTARpwnQS/ar+JpbNOUPkk+/NmKA3YOCQoVi69w/FK4SJR+2e0PCUwES86plYFkg5DzqmR4rpSVshe7dpq6Fl163ktQIfJRvQPvqdfRd/yYtJAMAls7Z7X5UfpjSQR97ndvOx2/cwkdxRTW3dKmWO5rQLhu0="

jobs:
  include:
    - stage: compile
      env: ANDROID="" ARCH="aarch64" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-aarch64-leia
          paths: .
    - env: ANDROID="" ARCH="aarch64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-aarch64-matrix
          paths: .
          
    - env: ANDROID="" ARCH="armv7" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-armv7-leia
          paths: .
    - env: ANDROID="" ARCH="armv7" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-armv7-matrix
          paths: .

    - env: ANDROID="" ARCH="x86_64" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-x86_64-leia
          paths: .
    - env: ANDROID="" ARCH="x86_64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-x86_64-matrix
          paths: .

    - env: ANDROID=" --android" ARCH="aarch64" KODI_VERSION="leia"
      workspaces:
        create:
          name: android-aarch64-leia
          paths: .
    - env: ANDROID=" --android" ARCH="aarch64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: android-aarch64-matrix
          paths: .
    
    - env: ANDROID=" --android" ARCH="armv7" KODI_VERSION="leia"
      workspaces:
        create:
          name: android-armv7-leia
          paths: .
    - env: ANDROID=" --android" ARCH="armv7" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: android-armv7-matrix
          paths: .

    - stage: deploy
      os: linux
      dist: xenial
      language: python
      env: KODI_VERSION="leia"
      workspaces:
        use:
          - linux-aarch64-leia
          - linux-aarch64-matrix
          - linux-armv7-leia
          - linux-armv7-matrix
          - linux-x86_64-leia
          - linux-x86_64-matrix
          - android-aarch64-leia
          - android-aarch64-matrix
          - android-armv7-leia
          - android-armv7-matrix
      install:
        - sudo apt-get update && sudo apt-get -y update
        - sudo apt install -y --no-install-recommends build-essential git unzip
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh leia
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh matrix
        - cd $HOME/.deploy/
        - git config credential.helper "store --file=.git/credentials"
        - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
        - git add .
        - git commit --allow-empty -m "$TRAVIS_COMMIT_MESSAGE"
        - git push

install:
  - sudo apt-get update && sudo apt-get -y update
  - sudo apt install -y --no-install-recommends build-essential git cmake unzip aria2 default-jdk python3

script:
  - bash -x $TRAVIS_BUILD_DIR/build_scripts/build-ia.sh
    --kodiversion $KODI_VERSION
    --no-apt-install
    --arch $ARCH 
    $ANDROID
  - mv $HOME/*.zip $TRAVIS_BUILD_DIR
