os: linux
dist: xenial
language: cpp
compiler: gcc
env:
  global:
    - APP_ID=inputstream.adaptive.testing
    - secure: "cEcDRo+aWtu0+qCS7oE7bZ23OzbFvsdT1I9P/W2i4VBU9FfDVxuXjX8rG3kUrN7xIxJnEWrJRtrhOHOVjzqZ5tnBsbTLS4mbII4HtPpGpOpxOdnDzeyOa93UgAyMD/SWUFzN/vhgn/LtG0oMqZcQDj7L4ccMkjz4h7075iMxQhSo8vmNyDIpjGwFrHFfifXSZoc0oZsszqXauxLFvPsaXpuTeO86iQdrJ4zUJw+OVnASD6UtQm1LcunJ3N8HsgGKzZGOjUZ2ZxhAf/+00pTOozh6nrlguPs2CgJuHC6J579dckT7OjkjTeGFbqH7bEITQpyH35tXffDs6lptpdcpLjp7m8McAG47CCAyYKmyKRMxTB9M5r4b9QwGsSCO9IxEQQHi/c+WR+bUOp/bYaVYygsJTT+1I0a8mrJ+vOrjhfK1O5pNKNv6Vd1WlTdo8pG6EXMw/P/HpNFpVfHPP0zCNbG+lBCogfaIwVkU+xNWCSXPZC0BbG8Jl/14W1M5scB4sFIYGtdsljOyHYbYTARpwnQS/ar+JpbNOUPkk+/NmKA3YOCQoVi69w/FK4SJR+2e0PCUwES86plYFkg5DzqmR4rpSVshe7dpq6Fl163ktQIfJRvQPvqdfRd/yYtJAMAls7Z7X5UfpjSQR97ndvOx2/cwkdxRTW3dKmWO5rQLhu0="

jobs:
  include:
    - stage: compile
      env: PLATFORM="linux" ARCH="aarch64" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-aarch64-leia
          paths: .
    - env: PLATFORM="linux" ARCH="aarch64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-aarch64-matrix
          paths: .
          
    - env: PLATFORM="linux" ARCH="armv7" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-armv7-leia
          paths: .
    - env: PLATFORM="linux" ARCH="armv7" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-armv7-matrix
          paths: .

    - env: PLATFORM="linux" ARCH="x86_64" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-x86_64-leia
          paths: .
    - env: PLATFORM="linux" ARCH="x86_64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-x86_64-matrix
          paths: .

    - env: PLATFORM="android" ARCH="aarch64" KODI_VERSION="leia"
      workspaces:
        create:
          name: android-aarch64-leia
          paths: .
    - env: PLATFORM="android" ARCH="aarch64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: android-aarch64-matrix
          paths: .
    
    - env: PLATFORM="android" ARCH="armv7" KODI_VERSION="leia"
      workspaces:
        create:
          name: android-armv7-leia
          paths: .
    - env: PLATFORM="android" ARCH="armv7" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: android-armv7-matrix
          paths: .
    
    - env: PLATFORM="darwin" ARCH="x86_64" KODI_VERSION="leia"
      os: osx
      osx_image: xcode10.2
      before_cache:
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      addons:
        homebrew:
          packages:
          - aria2
          - gnu-getopt
          - bash
          - coreutils
          update: true
      install:
        - brew link --force gnu-getopt
        - echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile && . ~/.bash_profile
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      workspaces:
        create:
          name: darwin-x86_64-leia
          paths: .
    - env: PLATFORM="darwin" ARCH="x86_64" KODI_VERSION="matrix"
      os: osx
      osx_image: xcode10.2
      before_cache:
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
        - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      addons:
        homebrew:
          packages:
          - aria2
          - gnu-getopt
          - bash
          - coreutils
          update: true
      install:
        - brew link --force gnu-getopt
        - echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile && . ~/.bash_profile
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      workspaces:
        create:
          name: darwin-x86_64-matrix
          paths: .

    - stage: deploy-main
      language: python
      workspaces:
        use:
          - android-aarch64-leia
          - android-aarch64-matrix
          - android-armv7-leia
          - android-armv7-matrix
          - darwin-x86_64-leia
          - darwin-x86_64-matrix
      install:
        - sudo apt-get update && sudo apt-get -y update
        - sudo apt install -y --no-install-recommends build-essential git unzip
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r main
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r main
    
    - stage: deploy-linux-aarch64
      language: python
      workspaces:
        use:
          - linux-aarch64-leia
          - linux-aarch64-matrix
      install:
        - sudo apt-get update && sudo apt-get -y update
        - sudo apt install -y --no-install-recommends build-essential git unzip
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r linux-aarch64
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r linux-aarch64
    
    - stage: deploy-linux-armv7
      language: python
      workspaces:
        use:
          - linux-armv7-leia
          - linux-armv7-matrix
      install:
        - sudo apt-get update && sudo apt-get -y update
        - sudo apt install -y --no-install-recommends build-essential git unzip
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r linux-armv7
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r linux-armv7
    
    - stage: deploy-linux-x86_64
      language: python
      workspaces:
        use:
          - linux-x86_64-leia
          - linux-x86_64-matrix
      install:
        - sudo apt-get update && sudo apt-get -y update
        - sudo apt install -y --no-install-recommends build-essential git unzip
        - pip3 install gitpython
        - git clone https://github.com/glennguy/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r linux-x86_64
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r linux-x86_64

install:
  - sudo apt-get update && sudo apt-get -y update
  - sudo apt install -y --no-install-recommends build-essential git cmake unzip aria2 default-jdk python3

script:
  - shopt -s expand_aliases
  - '[[ $TRAVIS_OS_NAME = "osx" ]] && alias bsh="/usr/local/bin/bash" && export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" || alias bsh="/bin/bash"'
  - bsh -x $TRAVIS_BUILD_DIR/build_scripts/build-ia.sh
    --kodiversion $KODI_VERSION
    --no-apt-install
    --arch $ARCH 
    --platform $PLATFORM
  - mv $HOME/*.zip $TRAVIS_BUILD_DIR
